export const enum OrderStatus {
  SUGGESSIONMANNUEL = 'SUGGESSIONMANNUEL',

  SUGGESSIONAUTOMATIK = 'SUGGESSIONAUTOMATIK',

  COMMANDE = 'COMMANDE',

  COMMANDEENCOURS = 'COMMANDEENCOURS',

  ENTREESTOCK = 'ENTREESTOCK',

  RECU = 'RECU',
}
